[build]
  command = "npm run build && npx next export"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
